### ISSUE TITLE
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0

### ISSUE THREAD

**Issue by nids126** [google-research/pegasus#116]
Facing this error while trying to run this command. Please help
!python3 pegasus/bin/train.py --params=aeslc_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/aeslc

Traceback (most recent call last):
  File "pegasus/bin/train.py", line 17, in <module>
    from pegasus.data import infeed
  File "/code/nidhi/pegasus/pegasus/data/infeed.py", line 18, in <module>
    from pegasus.data import all_datasets
  File "/code/nidhi/pegasus/pegasus/data/all_datasets.py", line 18, in <module>
    from pegasus.data import datasets
  File "/code/nidhi/pegasus/pegasus/data/datasets.py", line 22, in <module>
    import tensorflow_datasets as tfds
  File "/code/nidhi/pegasus_env/lib/python3.6/site-packages/tensorflow_datasets/__init__.py", line 51, in <module>
    from tensorflow_datasets import __init__py3 as api
  File "/code/nidhi/pegasus_env/lib/python3.6/site-packages/tensorflow_datasets/__init__py3.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/code/nidhi/pegasus_env/lib/python3.6/site-packages/tensorflow_datasets/core/__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "/code/nidhi/pegasus_env/lib/python3.6/site-packages/tensorflow_datasets/core/tf_compat.py", line 59, in ensure_tf_install
    "This version of TensorFlow Datasets requires TensorFlow "
ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0; Detected an installation of version 1.15.2. Please upgrade TensorFlow to proceed.

**Comment by JingqingZ** [comment]
I used

```
tensorflow-datasets==3.0.0
tfds-nightly==3.1.0.dev202006230105
```

**Comment by peterli1001** [comment]
> I used
> 
> ```
> tensorflow-datasets==3.0.0
> tfds-nightly==3.1.0.dev202006230105
> ```

It works for me on colab!! Thanks very much.

**Comment by nids126** [comment]
Worked perfectly! Thanks @JingqingZ :+1: 

> I used
> 
> ```
> tensorflow-datasets==3.0.0
> tfds-nightly==3.1.0.dev202006230105
> ```

**Comment by gymbeijing** [comment]
Thank you, it works!

> I used
> 
> ```
> tensorflow-datasets==3.0.0
> tfds-nightly==3.1.0.dev202006230105
> ```
