### ISSUE TITLE
Is it possible to fine-tune pegasus with wikihow dataset in google colaboratory?

### ISSUE THREAD

**Issue by Papillon6814** [google-research/pegasus#128]
Hello. I'm using pegasus for my school work.
I'd like to try to fine-tune pegasus with wikihow dataset.

I've downloaded wikihow csv data "wikihowAll.csv" and "wikihowSep.csv", then placed the files on the designated directory.
After some processes, I get able to run `train.py` in the environment.

But... in a some minutes, `train.py` stops due to OOM. So I tried to trim csv data to 10000 rows, 1000 rows, 100rows...
They all failed due to OOM after all. I'm wondering that it is not a csv problem.

If you know how to fine-tune with wikihow datasets, please let me know!

**Comment by JingqingZ** [comment]
OOM means the GPU runs out of memory. You may try GPU with larger memory or reduce the batch size.

**Comment by Papillon6814** [comment]
@JingqingZ 
Thank you for your answer.

```
%cd /content/drive/My Drive/Colab Notebooks/pegasus/
!python3 pegasus/bin/train.py --params=wikihow_all_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/wikihow \
--save_checkpoint_steps=10
```

I have run pegasus with this command. I referred the options from `train.py`.

```python
flags.DEFINE_string("master", "",
                    "Master tensorflow server (empty string for local).")
flags.DEFINE_string("model_dir", None,
                    "Output directory for model checkpoints.")
flags.DEFINE_string("params", None, "Name of params to use.")
flags.DEFINE_string("param_overrides", None,
                    "Param overrides as key=value pairs")
flags.DEFINE_integer("iterations_per_loop", 1000,
                     "Number of iterations to perform per TPU loop.")
flags.DEFINE_integer("num_shards", 1, "Number of TPU shards available.")
flags.DEFINE_boolean("use_tpu", False, "Whether to run on TPU accelerators.")
flags.DEFINE_integer("train_infeed_parallelism", 32,
                     "Number of infeed threads for training.")
flags.DEFINE_string("train_init_checkpoint", None,
                    "Initialize model or partial model from this checkpoint.")
flags.DEFINE_integer("train_warmup_steps", 10000, "Number of steps to warmup.")
flags.DEFINE_integer("save_checkpoints_steps", 1000,
                     "Save checkpoints every this many steps.")
flags.DEFINE_integer(
    "keep_checkpoint_max", 5,
    "The maximum number of recent checkpoint files to keep. "
    "As new files are created, older files are deleted.")
flags.DEFINE_string("train_steps_overrides", "",
                    ("List of integers. Override train steps from params."
                     "Ensure that model is saved at specified train steps."))
flags.DEFINE_integer("tfds_train_examples", -1,
                     "Set number of examples for tfds type data source")
```

`--save_checkpoint_steps=10` reduces the batch size, doesn't it? I'm not familiar with machine learning though...

**Comment by agenius5** [comment]
@Papillon6814 No, it doesn't. It means how often (every x number of steps) you want to save the checkpoints. Go to public_param.py inside params folder. There you will find registry for each dataset where you can change batch_size.

**Comment by Papillon6814** [comment]
@agenius5 
Thank you, I'll try it later!

**Comment by Papillon6814** [comment]
Hello.
I tried to run pegasus with batch size 4 this morning. Before the tryout, I ran pegasus with batch size 8(default). 
Then I got an error.

```bash
Dl Completed...: 0 url [00:00, ? url/s]
I1124 04:59:38.613306 140149540702080 dataset_builder.py:946] Generating split train
Shuffling and writing examples to /root/tensorflow_datasets/wikihow/all/1.2.0.incompleteOF4EY2/wikihow-train.tfrecord
  0% 0/10 [00:00<?, ? examples/s]I1124 04:59:38.632824 140149540702080 tfrecords_writer.py:230] Done writing /root/tensorflow_datasets/wikihow/all/1.2.0.incompleteOF4EY2/wikihow-train.tfrecord. Shard lengths: [10]
I1124 04:59:38.633213 140149540702080 dataset_builder.py:946] Generating split validation
Shuffling and writing examples to /root/tensorflow_datasets/wikihow/all/1.2.0.incompleteOF4EY2/wikihow-validation.tfrecord
ERROR:tensorflow:Error recorded from training_loop: No examples were yielded.
E1124 04:59:38.647563 140149540702080 error_handling.py:75] Error recorded from training_loop: No examples were yielded.
INFO:tensorflow:training_loop marked as finished
I1124 04:59:38.647747 140149540702080 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W1124 04:59:38.647857 140149540702080 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "pegasus/bin/train.py", line 94, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2987, in _call_input_fn
    return input_fn(**kwargs)
  File "/content/drive/My Drive/Colab Notebooks/pegasus/pegasus/data/infeed.py", line 41, in input_fn
    dataset = all_datasets.get_dataset(input_pattern, training)
  File "/content/drive/My Drive/Colab Notebooks/pegasus/pegasus/data/all_datasets.py", line 52, in get_dataset
    dataset, _ = builder.build(input_pattern, shuffle_files)
  File "/content/drive/My Drive/Colab Notebooks/pegasus/pegasus/data/datasets.py", line 200, in build
    dataset, num_examples = self.load(build_name, split, shuffle_files)
  File "/content/drive/My Drive/Colab Notebooks/pegasus/pegasus/data/datasets.py", line 158, in load
    data_dir=self.data_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 370, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 375, in download_and_prepare
    download_config=download_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1018, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 950, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1036, in _prepare_split
    shard_lengths, total_size = writer.finalize()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tfrecords_writer.py", line 213, in finalize
    self._shuffler.bucket_lengths, self._path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tfrecords_writer.py", line 97, in _get_shard_specs
    shard_boundaries = _get_shard_boundaries(num_examples, num_shards)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tfrecords_writer.py", line 120, in _get_shard_boundaries
    raise AssertionError("No examples were yielded.")
AssertionError: No examples were yielded.
```

I remember I could ran pegasus last week. What do I have to change in my environment?

**Comment by JingqingZ** [comment]
It seems the dataset is not loaded successfully.

**Comment by Papillon6814** [comment]
> @Papillon6814 No, it doesn't. It means how often (every x number of steps) you want to save the checkpoints. Go to public_param.py inside params folder. There you will find registry for each dataset where you can change batch_size.

Thank you, it solved the problem!
