### ISSUE TITLE
ValueError: Dataset name /pegasus/data/testdata/train_data.tfrecords is not found in registered datasets.

### ISSUE THREAD

**Issue by hgoyal194** [google-research/pegasus#142]
Please help me with this guys.

I am working with custom dataset fine-tuning.
I already registered with params.

```
!python3 pegasus/bin/train.py --params=custom_data \
--param_overrides=vocab_filename=ckpt/c4.unigram.newline.10pct.96000.model \
--train_init_checkpoint=ckpt/model.ckpt-1500000 \
--model_dir=ckpt/saved_model
```

when I ran above code it's given me the error of dataset name is not registered.

> Traceback (most recent call last):
  File "pegasus/bin/train.py", line 94, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2987, in _call_input_fn
    return input_fn(**kwargs)
  File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/infeed.py", line 41, in input_fn
    dataset = all_datasets.get_dataset(input_pattern, training)
  File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/all_datasets.py", line 51, in get_dataset
    builder = datasets.get_dataset(prefix)
  File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/datasets.py", line 30, in get_dataset
    dataset_name)
**ValueError: Dataset name /content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/testdata/train_data.tfrecords is not found in registered datasets.**

**Comment by agenius5** [comment]
Put correct path in corresponding dataset registry in following format:

`tfrecord:'path` for example: `tfrecord:/content/train.tfrecord'

**Comment by agenius5** [comment]
Are you sure it is tfrecords with s or just tfrecord?

**Comment by devilunraveled** [comment]
Any resolution?

**Comment by jayasridharmireddi** [comment]
> Please help me with this guys.
> 
> I am working with custom dataset fine-tuning. I already registered with params.
> 
> ```
> !python3 pegasus/bin/train.py --params=custom_data \
> --param_overrides=vocab_filename=ckpt/c4.unigram.newline.10pct.96000.model \
> --train_init_checkpoint=ckpt/model.ckpt-1500000 \
> --model_dir=ckpt/saved_model
> ```
> 
> when I ran above code it's given me the error of dataset name is not registered.
> 
> > Traceback (most recent call last):
> > File "pegasus/bin/train.py", line 94, in 
> > tf.app.run(main)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
> > _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> > File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
> > _run_main(main, args)
> > File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
> > sys.exit(main(argv))
> > File "pegasus/bin/train.py", line 89, in main
> > max_steps=train_steps)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
> > rendezvous.raise_errors()
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
> > six.reraise(typ, value, traceback)
> > File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
> > raise value
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
> > saving_listeners=saving_listeners)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
> > loss = self._train_model(input_fn, hooks, saving_listeners)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
> > return self._train_model_default(input_fn, hooks, saving_listeners)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
> > input_fn, ModeKeys.TRAIN))
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_input_fn
> > self._call_input_fn(input_fn, mode))
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2987, in _call_input_fn
> > return input_fn(**kwargs)
> > File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/infeed.py", line 41, in input_fn
> > dataset = all_datasets.get_dataset(input_pattern, training)
> > File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/all_datasets.py", line 51, in get_dataset
> > builder = datasets.get_dataset(prefix)
> > File "/content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/datasets.py", line 30, in get_dataset
> > dataset_name)
> > **ValueError: Dataset name /content/drive/MyDrive/pegasus_custom/pegasus/pegasus/data/testdata/train_data.tfrecords is not found in registered datasets.**

any solution to this?
