### ISSUE TITLE
Error when finetuning

### ISSUE THREAD

**Issue by matt9704** [google-research/pegasus#44]
Hi! I follow your readme instruction and run the code on google colab, but errors show up when running the finetuning part:
`!python3 pegasus/bin/train.py --params=reddit_tifu_long_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1 \
--train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 \
--model_dir=ckpt/pegasus_ckpt/reddit_tifu`

And the error log here:
Traceback (most recent call last):
  File "pegasus/bin/train.py", line 18, in <module>
    from pegasus.params import all_params  # pylint: disable=unused-import
  File "/content/pegasus/pegasus/params/all_params.py", line 18, in <module>
    from pegasus.params import pegasus_params
  File "/content/pegasus/pegasus/params/pegasus_params.py", line 21, in <module>
    from pegasus.eval import text_eval
  File "/content/pegasus/pegasus/eval/text_eval.py", line 22, in <module>
    from pegasus.eval.bleu import bleu_scorer
  File "/content/pegasus/pegasus/eval/bleu/bleu_scorer.py", line 18, in <module>
    import sacrebleu
  File "/usr/local/lib/python3.6/dist-packages/sacrebleu/__init__.py", line 25, in <module>
    from .tokenizers import TOKENIZERS, DEFAULT_TOKENIZER
ModuleNotFoundError: No module named 'sacrebleu.tokenizers'

The first time I run the code, this error doesn't show up and I finished finetuning part successfully. But this time I try to run the code again, I have this error. Why?

**Comment by JingqingZ** [comment]
Hi, what is your output `pip freeze | grep sacrebleu`? Mine is `sacrebleu==1.4.6`.
