### ISSUE TITLE
AI-platform compatibility

### ISSUE THREAD

**Issue by rohithsiddhartha** [google-research/pegasus#48]
Hey I would like to know pegasus AI-platform compatibility.
I tried to run it with reddiit_tifu dataset, there aren't any error logs as such but still job isn't being executed and stops after
Saving checkpoints for 0 into gs://movie-genre/text_summarization/ckpt/pegasus_ckpt/reddit_tifu/model.ckpt.
what could be the possible reason for this to happen and is there to fix this ?

Bash file which is used to submit AI-platform job has been pasted below.

configuration file is 
trainingInput:
  masterType: complex_model_l_gpu
  scaleTier: CUSTOM
# Google cloud arguments
REGION="us-east1"
BUCKET_NAME="movie-genre"
BUCKET_OBJECT="text_summarization"
DATASET="reddit_tifu_long_transformer"
CKPT="reddit_tifu"
BUCKET_PATH="movie-genre/text_summarization/ckpt"
# Module mode arguments
# Jobs running arguments
TRAIN_METHOD="train"
TRAINER_PACKAGE_PATH="$(pwd)/pegasus/"
now=$(date +"%Y%m%d_%H%M%S")
MAIN_TRAINER_MODULE="pegasus.train"
PACKAGE_STAGING_PATH="gs://$BUCKET_NAME/"

TRAIN_INIT_CHECKPOINT="gs://$BUCKET_PATH/pegasus_ckpt/model.ckpt-1500000"
VOCAB_FILENAME="gs://$BUCKET_PATH/pegasus_ckpt/c4.unigram.newline.10pct.96000.model"

JOB_NAME="PEGASUS_l"_"$CKPT"_"$now"
MODEL_DIR="gs://$BUCKET_PATH/pegasus_ckpt/$CKPT"
MODEL_DIRECTORY="gs://$BUCKET_NAME/BUCKET_OBJECT/pegasus/logs"_"$JOB_NAME"_"$now/"
CONFIG="config.yaml"
gcloud ai-platform jobs submit training $JOB_NAME \
    --staging-bucket $PACKAGE_STAGING_PATH \
    --runtime-version 1.15 \
    --python-version 3.7 \
    --package-path $TRAINER_PACKAGE_PATH \
    --module-name $MAIN_TRAINER_MODULE \
    --region $REGION \
    --config $CONFIG \
    -- \
    --params=$DATASET \
    --param_overrides=vocab_filename=$VOCAB_FILENAME \
    --train_init_checkpoint=$TRAIN_INIT_CHECKPOINT \
    --model_dir=$MODEL_DIR

If I use the same bash file for job submission for xsum and wikihow dataset it asked me download dataset at AssertionError: Manual directory /root/tensorflow_datasets/downloads/manual does not exist or is empty. Create it and download/extract dataset artifacts in there. Additional instructions: 

For big_patent: "The dataset you're trying to generate is using Apache Beam. Beam"
ValueError: The dataset you're trying to generate is using Apache Beam. Beamdatasets are usually very large and should be generated separately.
Let's suppose if I integrate dataflow pipeline, how am I supposed to use it while training ?

In local it was possible to download dataset in the required folder but where as in AI-platform,  is there a way to access the dataset from bucket,  whereever there is a requirement of manual download of dataset to root directory of tfds.

**Comment by JingqingZ** [comment]
> If I use the same bash file for job submission for xsum and wikihow dataset it asked me download dataset at AssertionError: Manual directory /root/tensorflow_datasets/downloads/manual does not exist or is empty. Create it and download/extract dataset artifacts in there. 

Does the guide help https://www.tensorflow.org/datasets/catalog/xsum regarding the manual download?

I am not sure about the other questions so I will assign a label to call for help.

**Comment by rohithsiddhartha** [comment]
> > If I use the same bash file for job submission for xsum and wikihow dataset it asked me download dataset at AssertionError: Manual directory /root/tensorflow_datasets/downloads/manual does not exist or is empty. Create it and download/extract dataset artifacts in there.
> 
> Does the guide help https://www.tensorflow.org/datasets/catalog/xsum regarding the manual download?
> No this detail didn't help as it wasn't mentioned which file to download either a tar.gz of json file or create gz file from downloaded json or text files.
> wiki thing was pretty clear as it specifically suggested me to download csv files and then place it in the folder.

I found a fix for this manual download part  replace data_dir in pegasus/data/datasets.py class TFDSDataset line 158 with the bucket location gs://.../tensorflow_datasets/.. . So while execution it took file from bucket instead of looking in the local tensorflow_datasets directory.

I would like to know regarding big_patent dataset is there any requirement of nltk to process the dataset ?

**Comment by rohithsiddhartha** [comment]
Hey JingqingZ,I tried to use tpu

by mentioning use_tpu as True in train.py file proving below configuration file for AI-platform
trainingInput:
  masterType: complex_model_m
  scaleTier: CUSTOM
  workerType: cloud_tpu
  workerCount: 1  

Then I encountered this ERROR:
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/root/.local/lib/python3.7/site-packages/pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    hooks.extend(self._convert_train_steps_to_hooks(steps, max_steps))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2901, in _convert_train_steps_to_hooks
    if ctx.is_running_on_cpu():
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 462, in is_running_on_cpu
    self._validate_tpu_configuration()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 632, in _validate_tpu_configuration
    'are {}.'.format(tpu_system_metadata.devices))
RuntimeError: Cannot find any TPU cores in the system. Please double check Tensorflow master address and TPU worker(s). Available devices are (_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 7697856157347333226), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 17543736472864247047)).



So I added piece of code in train.py file to access tpu as suggested by a friend.

def main(_):
  params = registry.get_params(FLAGS.params)(FLAGS.param_overrides)
  if FLAGS.use_tpu:
    tpu_config_env = os.environ.get('TPU_CONFIG')
    tpu_node = json.loads(tpu_config_env)
    FLAGS.master =[tpu_node['tpu_node_name']]
  if FLAGS.tfds_train_examples > 0:
    if not params.train_pattern.startswith("tfds:"):
      raise ValueError("expect tfds type dataset.")
    params.train_pattern += "-take_%d" % FLAGS.tfds_train_examples

After passing this I got another error which is mentioned below

Traceback (most recent call last):
message: "Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.7/site-packages/pegasus/bin/train.py", line 102, in <module>
    tf.app.run(main)
  File "/root/.local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/root/.local/lib/python3.7/site-packages/pegasus/bin/train.py", line 97, in main
    max_steps=train_steps)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    hooks.extend(self._convert_train_steps_to_hooks(steps, max_steps))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2901, in _convert_train_steps_to_hooks
    if ctx.is_running_on_cpu():
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 462, in is_running_on_cpu
    self._validate_tpu_configuration()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 623, in _validate_tpu_configuration
    num_cores = self.num_cores
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 360, in num_cores
    metadata = self._get_tpu_system_metadata()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 285, in _get_tpu_system_metadata
    query_topology=self.model_parallelism_enabled))
  File "/root/.local/lib/python3.7/site-packages/tensorflow_core/python/tpu/tpu_system_metadata.py", line 85, in _query_tpu_system_metadata
    cluster_def)) as sess:
  File "/root/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/root/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "cmle-training-16283632315969759740-tpu" config: operation_timeout_in_ms: 300000} Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
"   

help me in fixing this.

I tried to run big patent/all with gpu standard_v100 with batch_size of 8 yet I experienced Resource Exhausted OOM error.

gcloud compute instances create \
  ${VM_NAME} \
  --zone=${ZONE} \
  --machine-type=n1-highmem-8 \
  --accelerator type=nvidia-tesla-v100,count=1 \
  --boot-disk-size=500GB \
  --image-project=ml-images \
  --image-family=tf-1-15 \
  --maintenance-policy TERMINATE --restart-on-failure 

Did you run all your training and finetuning jobs on VM instance? If Yes
Does this configuration work for all the finetuning jobs? especially big_patent/all as it is the largest dataset which is used to finetune and train it for 50000 steps and with batch size of 8.

How did you make use of tpu?  BY adding TPU on VM instance and then ran train.py file with use_tpu=True.

Help me in fixing the error

**Comment by rohithsiddhartha** [comment]
I was able to use TPU in AI-Platform for pegasus after changing code in estimator_utils.py and adding some input arguments to train.py and evaluate.py. 
I added those inputs with reference from run_squad_v2.py in ALBERT 
https://github.com/google-research/albert/blob/master/run_squad_v2.py#L152 

Changes done:
Input arguments: tpu_zone, tpu_name and gcp_project.
Estimator: Changes are done while defining RunConfig and added tpu_cluster_resolver.

One might face error which states master and cluster both are defined to get rid of this you should change master to None.  
Code wise changes are mentioned in above comment and link for the same is provided below.
https://github.com/google-research/pegasus/issues/48#issuecomment-659208930

I hope this helps the users who are willing to use AI-platform with TPU.
I'm closing this issue as it is resolved.
