### ISSUE TITLE
TensorFlow Serving support

### ISSUE THREAD

**Issue by akashjaswal** [google-research/pegasus#65]
Any plans of extending Pegasus to export models as TFHub modules or to run directly with TensorFlow Server? [Tensor2Tensor has an easy to use model exporter/server](https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/serving) which plugs into the tensorflow-serving-api to provide easy ways to query.

**Comment by JingqingZ** [comment]
Hi, I am sorry there is no recent plan to export PEGASUS to TFHub from our side.

**Comment by TheRockXu** [comment]
@akashjaswal  I created a servable model by training cnn_dailymail on pegasus, you can download it [here](https://drive.google.com/file/d/1FVzZto4bf5_TCmRy3tNeirhPDdLrvum5/view?usp=sharing). It works with tf2. You can try to deploy it if you want.

I also created a [repo](https://github.com/TheRockXu/pegasus-demo) that you can try an end to end summarization demo.

**Comment by codemeterr** [comment]
Thank you, @TheRockXu !
However, when I try to run this, I receive the following Syntax error: 

`Traceback (most recent call last):
  File "test_example.py", line 2, in <module>
    import public_parsing_ops
  File "/Users/emiel/pegasus-demo-master/public_parsing_ops.py", line 29
    def create_text_encoder(encoder_type: str, vocab_filename: str):
                                        ^
SyntaxError: invalid syntax`

**Comment by TheRockXu** [comment]
@codemeterr Did you use Python2.7 to run the code? Please use Python3 because it supports typed parameters.

**Comment by codemeterr** [comment]
Thank you, @TheRockXu , that seems to work!
However, the summary seems to be extractive, rather than abstractive.
Do you know what's up with that?

**Comment by TheRockXu** [comment]
@codemeterr For some yes. It could probably perform better if it was trained longer and it depends on the dataset. If it was trained on gigaword dataset, it'd be highly abstractive. I'll put up that model later.

**Comment by chetanambi** [comment]
@TheRockXu Could you please share the steps for fine-tuning on gigaword. I tried to follow the steps mentioned in README.md but I am running into issues. Could you please share the steps.
