### ISSUE TITLE
Cert issue while training

### ISSUE THREAD

**Issue by sadiayousafzai036** [google-research/pegasus#73]
Hi,

When I try to run the Pegasus training code, I can see some authentication issues with gcloud. Does anyone know how to resolve it?
![error](https://user-images.githubusercontent.com/5640232/88342532-695cd700-ccf4-11ea-9158-2c32c2e9fb8b.PNG)

**Comment by sadiayousafzai036** [comment]
2020-07-23 14:57:33.895960: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Aborted: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'".

**Comment by sadiayousafzai036** [comment]
SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
         when reading metadata of gs://tfds-data/dataset_info/aeslc/1.0.0

**Comment by sadiayousafzai036** [comment]
full error trace:
 python3 pegasus/bin/train.py --params=aeslc_transformer --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newli                             ne.10pct.96000.model --train_init_checkpoint=ckpt/pegasus_ckpt/model.ckpt-1500000 --model_dir=ckpt/pegasus_ckpt/aeslc
WARNING:tensorflow:From pegasus/bin/train.py:94: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /home/014321333/pegasus/pegasus/ops/public_parsing_ops.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instea                             d.

W0724 17:51:00.689812 140302261294912 module_wrapper.py:139] From /home/014321333/pegasus/pegasus/ops/public_parsing_ops.py:93: The name tf.gfile.GFile is depre                             cated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /home/014321333/pegasus/pegasus/params/estimator_utils.py:49: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto                              instead.

W0724 17:51:00.859471 140302261294912 module_wrapper.py:139] From /home/014321333/pegasus/pegasus/params/estimator_utils.py:49: The name tf.ConfigProto is depre                             cated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:Estimator's model_fn (<function _estimator_model_fn.<locals>.model_fn at 0x7f99f5cb5a60>) includes params argument, but params are not passed                              to Estimator.
W0724 17:51:00.860015 140302261294912 estimator.py:1994] Estimator's model_fn (<function _estimator_model_fn.<locals>.model_fn at 0x7f99f5cb5a60>) includes para                             ms argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_model_dir': 'ckpt/pegasus_ckpt/aeslc', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_                             save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol':                              None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_servic                             e': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f99f5cb75c0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_c                             luster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_pe                             r_loop=1000, num_shards=None, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims                             =None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
I0724 17:51:00.860425 140302261294912 estimator.py:212] Using config: {'_model_dir': 'ckpt/pegasus_ckpt/aeslc', '_tf_random_seed': None, '_save_summary_steps':                              100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol':                              None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_servic                             e': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f99f5cb75c0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_c                             luster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_pe                             r_loop=1000, num_shards=None, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims                             =None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
I0724 17:51:00.860644 140302261294912 tpu_context.py:220] _TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
W0724 17:51:00.860869 140302261294912 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:From /home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVari                             able.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0724 17:51:00.866306 140302261294912 deprecation.py:506] From /home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variabl                             e_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a f                             uture version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (                             from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0724 17:51:00.866661 140302261294912 deprecation.py:323] From /home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/training_ut                             il.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2020-07-24 17:51:00.886801: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:01.029998: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:01.719849: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:02.308129: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:03.424191: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:05.888034: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:09.454666: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:16.845897: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:29.866531: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:51:56.269460: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
2020-07-24 17:52:29.066692: W tensorflow/core/platform/cloud/google_auth_provider.cc:178] All attempts to get a Google authentication bearer token failed, retur                             ning an empty token. Retrieving token from files failed with "Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cer                             t (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none". Retrieving token from GCE failed with "Cancelled: GCE check skipped due to presence of $NO_GCE_CHECK environment variable.".
ERROR:tensorflow:Error recorded from training_loop: __init__() missing 2 required positional arguments: 'op' and 'message'
E0724 17:52:29.073343 140302261294912 error_handling.py:75] Error recorded from training_loop: __init__() missing 2 required positional arguments: 'op' and 'mes                             sage'
INFO:tensorflow:training_loop marked as finished
I0724 17:52:29.073671 140302261294912 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0724 17:52:29.073852 140302261294912 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 399, in try_reraise
    yield
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 244, in builder
    return builder_cls(name)(**builder_kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 206, in __init__
    self.info.initialize_from_bucket()
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py", line 423, in initialize_from_bucket
    data_files = gcs_utils.gcs_dataset_info_files(self.full_name)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gcs_utils.py", line 72, in gcs_dataset_info_files
    return gcs_listdir(posixpath.join(GCS_DATASET_INFO_DIR, dataset_dir))
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gcs_utils.py", line 65, in gcs_listdir
    if _is_gcs_disabled or not tf.io.gfile.exists(root_dir):
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 280, in file_exists_v2
    pywrap_tensorflow.FileExists(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code                              77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
         when reading metadata of gs://tfds-data/dataset_info/aeslc/1.0.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pegasus/bin/train.py", line 94, in <module>
    tf.app.run(main)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1025, in _get_features_and_labels_from_i                             nput_fn
    self._call_input_fn(input_fn, mode))
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2987, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/014321333/pegasus/pegasus/data/infeed.py", line 41, in input_fn
    dataset = all_datasets.get_dataset(input_pattern, training)
  File "/home/014321333/pegasus/pegasus/data/all_datasets.py", line 52, in get_dataset
    dataset, _ = builder.build(input_pattern, shuffle_files)
  File "/home/014321333/pegasus/pegasus/data/datasets.py", line 200, in build
    dataset, num_examples = self.load(build_name, split, shuffle_files)
  File "/home/014321333/pegasus/pegasus/data/datasets.py", line 158, in load
    data_dir=self.data_dir)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 368, in load
    dbuilder = builder(name, data_dir=data_dir, **builder_kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 244, in builder
    return builder_cls(name)(**builder_kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 401, in try_reraise
    reraise(*args, **kwargs)
  File "/home/014321333/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 392, in reraise
    six.reraise(exc_type, exc_type(msg), exc_traceback)
TypeError: __init__() missing 2 required positional arguments: 'op' and 'message'
