### ISSUE TITLE
ResourceExhaustedError during Finetuning on arxiv, batch_size = 1 

### ISSUE THREAD

**Issue by Kkkassini** [google-research/pegasus#95]
My environment: 
--------------------------------------------
GPU: Tesla T4 16G 

CentOS 8.1
CUDA 10.0
NVIDIA-SMI 410.48                 Driver Version: 440.56  
cudnn 7.0
python 3.6.8
tensorboardX             1.6
tensorflow               1.15.3
tensorflow-addons        0.11.2
tensorflow-datasets      3.2.1
tensorflow-estimator     1.15.1
tensorflow-gan           2.0.0
tensorflow-gpu           1.15.2
tensorflow-hub           0.9.0
tensorflow-metadata      0.23.0
tensorflow-probability   0.7.0
tensorflow-text          1.15.0rc0
---------------------------------------------

During the training on arxiv dataset, with batch_size=1, got ResourceExhaustedError:

-----------------------------------------------------------------------------------------------
python pegasus/bin/evaluate.py --params=arxiv_transformer \
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6 \
--model_dir=ckpt/pegasus_ckpt/arxiv
------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "pegasus/bin/train.py", line 94, in <module>
    tf.app.run(main)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[8,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node encoder/layer_8/self_attention/Softmax (defined at /home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[8,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node encoder/layer_8/self_attention/Softmax (defined at /home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[softmax_cross_entropy_loss/value/_9835]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'encoder/layer_8/self_attention/Softmax':
  File "pegasus/bin/train.py", line 94, in <module>
    tf.app.run(main)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pegasus/bin/train.py", line 89, in main
    max_steps=train_steps)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/xingjian/kvenv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1994, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/opt/pegasus/pegasus/params/estimator_utils.py", line 105, in model_fn
    loss, outputs = model_params.model()(features, training)
  File "/opt/pegasus/pegasus/models/transformer.py", line 91, in __call__
    context = self._encode(features, training)
  File "/opt/pegasus/pegasus/models/transformer.py", line 72, in _encode
    None, None)
  File "/opt/pegasus/pegasus/layers/transformer_block.py", line 100, in stack
    decode_i=decode_i)
  File "/opt/pegasus/pegasus/layers/transformer_block.py", line 65, in __call__
    y_BxIxD, bias_BxIxI, training, cache=cache, decode_i=decode_i)
  File "/opt/pegasus/pegasus/layers/attention.py", line 94, in __call__
    x, x, bias, training, cache=cache, decode_i=decode_i)
  File "/opt/pegasus/pegasus/layers/attention.py", line 78, in __call__
    alignment_BxHxIxM = tf.nn.softmax(logits_BxHxIxM)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2958, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2891, in _softmax
    return compute_op(logits, name=name)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 11376, in softmax
    "Softmax", logits=logits, name=name)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/xingjian/kvenv/lib64/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Check top: CPU usage 200%, RAM usage 15%
Check nvidia-smi: 0 volatile GPU-Util but high GPU Memory Usage(16G almost full)

**Comment by JingqingZ** [comment]
> (1) Resource exhausted: OOM when allocating tensor with shape[8,16,1024,1024] and type float on

For the arxiv dataset, our model takes 1024 tokens as input which lead to large memory cost by the Transformer Encoder. A potential solution to make the code runnable (but may harm accuracy) is to reduce `max_input_len` to a smaller number like 512 by `--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=5,beam_alpha=0.6,max_input_len=512`
