### ISSUE TITLE
Flag --params must have a value other than None

### ISSUE THREAD

**Issue by SnigdhaBiswas** [google-research/pegasus#97]
I was trying to get the summary for custom input.

I ran the following command:
!python3 pegasus/bin/evaluate.py \-- params=test_transformer \ --param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=2,beam_alpha=0.6 \-- model_dir=ckpt/pegasus_ckpt/

I'm getting the following error:

WARNING:tensorflow:From pegasus/bin/evaluate.py:152: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

WARNING:tensorflow:From pegasus/bin/evaluate.py:153: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 541, in _assert_validators
    validator.verify(self)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_validators.py", line 82, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --params must have a value other than None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pegasus/bin/evaluate.py", line 153, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 294, in run
    flags_parser,
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 363, in _run_init
    flags_parser=flags_parser,
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 213, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 649, in __call__
    self.validate_all_flags()
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 523, in validate_all_flags
    self._assert_validators(all_validators)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 544, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --params=None: Flag --params must have a value other than None.

How can this issue be resolved?

**Comment by JingqingZ** [comment]
Hi, the flag `--params` wasn't successfully captured by the script.

I notice there are some spaces in your command, which might cause this issue. Try
```
!python3 pegasus/bin/evaluate.py --params=test_transformer \ 
--param_overrides=vocab_filename=ckpt/pegasus_ckpt/c4.unigram.newline.10pct.96000.model,batch_size=1,beam_size=2,beam_alpha=0.6 \ 
--model_dir=ckpt/pegasus_ckpt/
```

**Comment by SnigdhaBiswas** [comment]
It worked. Thank you!
